Einsum
GQCG/GQCP pull request #772
Opened 2020-11-04 16:17 UTC by xdvriend

**Short description**
This PR aims to complete and test the ensue API introduced by @lelemmen .

**Related issues**
closes #711 

**Additional context**
The first step was debugging the current implementation. By comparing it to the results from the same `einsum` operations using `numpy`, this should now be done.
What's next for this PR:

- [ ]  Write appropriate tests for the einsum API.

- [ ]  Add additional API, which follows `numpy` more closely. 

- [ ] Check code for contractions and replace them with the `einsum` API where possible.

**Don't forget:**
- [ ] if new files are created: update the Doxygen file, the collective gqcp.hpp header and the CMake files

2020-11-05 14:17 UTC, xdvriend commented
@lelemmen I have added an initial implementation on th more `numpy`-like API. However, at the moment, it still requires a template argument `N`to be specified. Is there a way to circumvent this? If it is possible to calculate this `N`value within the second `einsum`method, I would be able to completely create the `tensor1.einsum("ijkl,jk->il", tensor2)` API.

2020-11-09 14:21 UTC, xdvriend commented
@lelemmen, I have noticed that the einsum API can't be used for something like `Tensor.einsum<2>("pq, qp ->", tensor2)`. Would you like me to provide this implementation as well, or would you leave this as it is now? 

Adding this implementation would allow me to rewrite several other methods using einsum, like `calculateElectronicEnergy()`of the Hartree-Fock methods and several `calculateExpectationValue()` methods. 

Other than that the einsum implementation should be finished.

I also added a method that transforms a tensor to a matrix, since this was often used in several methods, and I believed this made things a little clearer.

2020-11-09 14:23 UTC, lelemmen commented
I think your extra use case is quite useful, so could you add it to the code as well? Feel free to assign an extra estimate **directly on this PR**, indicating that this PR has become larger than the issue(s) it is trying to close.

2020-11-09 15:18 UTC, xdvriend commented
Subsequent implementations tackled in this PR:

- [ ]  Add ability to use einsum to contract over all axis indices.

- [ ] Replace `.contract()` with `.einsum` where possible, including contractions over all indices.

2020-11-10 10:39 UTC, lelemmen commented
> With these implementations done I believe the `contractWithMatrix()` API of the `SquareRankFourTensor` is now redundant, since `einsum()` has the possibility to contract a tensor with a matrix. Am I missing something or am I free to delete this method and replace it's uses with the corresponding `einsum()`(@lelemmen)?

Yes, you can delete this!

> EDIT: Upon further inspection, it seems the `contractWithMAtrix()` method is only used in `AtomicDecompositionParameters.cpp`, which looks to be disabled at the moment. Since it is very little work to replace these cases with an `einsum()` equivalent, I'm happy to do so. But, since testing is disabled for this module, I'm also happy to just leave it as it is now. Let me know what you prefer!

Indeed, this application is currently disabled. (See also #630, it can be re-enabled once the Mulliken partitioning works for two-electron operators). Anyways, I think you can leave that code as it is, since it's going to disappear anyways.

2020-11-10 11:19 UTC, lelemmen requested changes
This is really awesome!

For the review, I've added some suggestions on improving the `asMatrix()` API. Also, The RHF and UHF QCModel files should be cleaned up like I did in the GHF file.

There's still some clean-up to be done. I'd like to ask you to be more diligent about your documentation (they're supposed to be real sentences).

2020-11-10 11:19 UTC, lelemmen commented on gqcp/include/Operator/SecondQuantized/SimpleSQTwoElectronOperator.hpp
>          }
Looks a lot better, nice!!!

2020-11-10 11:19 UTC, lelemmen commented on gqcp/include/QCModel/HF/GHF.hpp
> +        const auto& g = sq_hamiltonian.twoElectron().parameters();
```suggestion
```

I've moved this again to below.

2020-11-10 11:19 UTC, lelemmen commented on gqcp/include/QCModel/HF/GHF.hpp
> +        const auto& g = sq_hamiltonian.twoElectron().parameters();
```suggestion
```

I've moved this to below.

2020-11-10 11:19 UTC, lelemmen commented on gqcp/include/QCModel/HF/GHF.hpp
> +        auto K_bb = K_bb_tensor.toMatrix(K_bb_tensor.dimension(0), K_bb_tensor.dimension(1));
```suggestion
        const auto& g = sq_hamiltonian.twoElectron().parameters();
        const auto K_aa= g.template einsum<2>("ijkl,kj->il", P_aa).asMatrix();
        const auto K_ab = g.template einsum<2>("ijkl,kj->il", P_ba).asMatrix();
        const auto K_ba = g.template einsum<2>("ijkl,kj->il", P_ab).asMatrix();
        const auto K_bb = g.template einsum<2>("ijkl,kj->il", P_bb).asMatrix();
```

2020-11-10 11:19 UTC, lelemmen commented on gqcp/include/Mathematical/Representation/Tensor.hpp
>      }
I think you can clean up this API even more. Could you also add the appropriate `enable_if`?

```suggestion
    /**
     *  @return This rank-two tensor as a matrix.
     */
    const GQCP::Matrix<Scalar> asMatrix() const {

        const auto rows = this->dimension(0);
        const auto cols = this->dimension(1);

        return GQCP::Matrix<Scalar>(Eigen::Map<const Eigen::Matrix<Scalar, Eigen::Dynamic, Eigen::Dynamic>>(this->data(), rows, cols));
    }
```

2020-11-10 11:19 UTC, lelemmen commented on gqcp/include/QCModel/HF/GHF.hpp
> +        Tensor<Scalar, 2> Jb_tensor = g.template einsum<2>("ijkl,kl->ij", P_bb);
```suggestion
        const auto Ja_tensor = g.template einsum<2>("ijkl,kl->ij", P_aa).asMatrix();
        const auto Jb_tensor = g.template einsum<2>("ijkl,kl->ij", P_bb).asMatrix();
```

2020-11-10 11:19 UTC, lelemmen commented on gqcp/include/QCModel/HF/GHF.hpp
> +        auto Jb = Jb_tensor.toMatrix(Jb_tensor.dimension(0), Jb_tensor.dimension(1));
```suggestion
```

2020-11-10 11:19 UTC, lelemmen commented on gqcp/tests/Mathematical/Representation/Tensor_test.cpp
> +
Add documentation before the test, like you would for a function.

2020-11-10 11:19 UTC, lelemmen commented on gqcp/tests/Mathematical/Representation/Tensor_test.cpp
> +}
Check the punctuation and capitalization of the documentation, please.

Also, I see that you're testing multiple things: it's better split this up in different test cases, each specifically testing one part of the API.

2020-11-10 12:20 UTC, xdvriend commented on gqcp/include/Mathematical/Representation/Tensor.hpp
> +                intermediate_indices.erase(i - 1, 1);
Exactly! And I'll be sure to add it.

2020-11-10 13:00 UTC, xdvriend commented on gqcp/include/Mathematical/Representation/Tensor.hpp
> +    Tensor<Scalar, LHSRank + RHSRank - 2 * N> einsum(std::string contraction_string, const Tensor<Scalar, RHSRank>& rhs) const {
The `contraction_string`cannot be `const`since it is adjusted by the boost library when removing spaces and symbols.

2020-11-10 16:33 UTC, xdvriend commented
I have adjusted everything as you mentioned it and replaced the final instances of the old `contractWithMatrix()` API. The only thing I didn't change was the following piece of code from the RHF `QCModel`:

![Screenshot 2020-11-10 at 17 28 07](https://user-images.githubusercontent.com/54795591/98702086-483ef580-237a-11eb-9f6d-133a0afcb775.png)

- I'm not using `const auto` since it ill automatically recognise it as an `Eigen::Tensor`, which can't use the `.asMatrix()` method.
- I know I should be able to write it in one line, by adding `.asMatrix()` at the end of the einsum, but for some reason, this causes the `properties_test.cpp`and `constrained_RHF_test.cpp` to fail. Because of this I have left it as it is now.

2020-11-10 17:27 UTC, lelemmen approved these changes
Your remarks sounds good to me. This PR is good to go! 🎉

2020-11-10 17:29 UTC, merged